# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-21 03:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moncrieffeLTS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='isbn',
            field=models.IntegerField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='media_type',
            field=models.CharField(max_length=128),
        ),
    ]
