# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-21 04:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moncrieffeLTS', '0002_auto_20170620_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='isbn',
            field=models.IntegerField(unique=True),
        ),
    ]
