# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-21 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moncrieffeLTS', '0003_auto_20170621_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='slug',
            field=models.SlugField(blank=True, default=''),
        ),
    ]
